{{-- resources/views/reports/aging.blade.php --}}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: DejaVu Sans, sans-serif; font-size: 9px; color: #1C1F26; margin: 20px; }
  .letterhead { text-align: center; border-bottom: 1.5px solid #1C1F26; padding-bottom: 8px; margin-bottom: 12px; }
  .letterhead h1 { font-size: 12px; font-weight: bold; margin: 0 0 2px; }
  .letterhead p  { font-size: 8px; color: #555; margin: 0; }
  .letterhead h2 { font-size: 14px; font-weight: bold; margin: 6px 0 2px; }
  .meta { font-size: 8px; color: #555; margin-bottom: 12px; display: flex; justify-content: space-between; }
  .bucket-header { background: #1C3557; color: #fff; font-size: 9px; font-weight: bold; padding: 4px 8px; margin-top: 12px; }
  .bucket-header.amber { background: #854F0B; }
  .bucket-header.red   { background: #A32D2D; }
  table { width: 100%; border-collapse: collapse; }
  th { background: #e8eef5; color: #1C1F26; font-size: 7.5px; text-transform: uppercase; padding: 4px 8px; text-align: left; }
  td { padding: 4px 8px; border-bottom: 0.5px solid #e0e0e0; font-size: 8.5px; }
  .right { text-align: right; }
  .footer { margin-top: 16px; font-size: 7px; color: #888; border-top: 0.5px solid #ccc; padding-top: 6px; }
  .summary-row { display: flex; gap: 8px; margin-bottom: 12px; }
  .stat { background: #f5f5f0; border: 0.5px solid #ddd; border-radius: 4px; padding: 6px 10px; flex: 1; }
  .stat-label { font-size: 7px; text-transform: uppercase; letter-spacing: .4px; color: #666; }
  .stat-val   { font-size: 13px; font-weight: bold; }
</style>
</head>
<body>
<div class="letterhead">
  <h1>{{ strtoupper($profile->name) }}</h1>
  <p>{{ $profile->address }} · CDA Reg. No. {{ $profile->cda_reg_no ?? '___' }}</p>
  <h2>LOAN AGING REPORT</h2>
</div>
<div class="meta">
  <span>As of: {{ $as_of_date }}</span>
  <span>Generated by: {{ $generated_by }} · {{ $generated_at }}</span>
</div>

<div class="summary-row">
  <div class="stat"><div class="stat-label">0–30 days</div><div class="stat-val" style="color:#0F6E56">₱{{ number_format($summary['0_30']['balance'],2) }}</div></div>
  <div class="stat"><div class="stat-label">31–60 days</div><div class="stat-val" style="color:#854F0B">₱{{ number_format($summary['31_60']['balance'],2) }}</div></div>
  <div class="stat"><div class="stat-label">61–90 days</div><div class="stat-val" style="color:#854F0B">₱{{ number_format($summary['61_90']['balance'],2) }}</div></div>
  <div class="stat"><div class="stat-label">90+ days</div><div class="stat-val" style="color:#A32D2D">₱{{ number_format($summary['90_plus']['balance'],2) }}</div></div>
</div>

@foreach(['0_30' => ['0–30 days', ''], '31_60' => ['31–60 days', 'amber'], '61_90' => ['61–90 days', 'amber'], '90_plus' => ['90+ days (critical)', 'red']] as $key => [$label, $cls])
@if(count($buckets[$key]) > 0)
<div class="bucket-header {{ $cls }}">{{ $label }} — {{ count($buckets[$key]) }} period(s) · ₱{{ number_format(collect($buckets[$key])->sum('balance'), 2) }}</div>
<table>
  <thead><tr>
    <th>Member</th><th>Loan #</th><th>Type</th>
    <th class="right">Due date</th><th class="right">Balance (₱)</th>
    <th class="right">Penalty (₱)</th><th class="right">Days overdue</th>
  </tr></thead>
  <tbody>
    @foreach($buckets[$key] as $row)
    <tr>
      <td>{{ $row['member_name'] }} <span style="color:#666;font-size:7.5px">({{ $row['member_no'] }})</span></td>
      <td>{{ $row['loan_no'] }}</td>
      <td>{{ $row['loan_type_label'] }}</td>
      <td class="right">{{ $row['due_date'] }}</td>
      <td class="right">{{ number_format($row['balance'],2) }}</td>
      <td class="right" @if($row['penalty_amount']>0) style="color:#A32D2D" @endif>{{ number_format($row['penalty_amount'],2) }}</td>
      <td class="right">{{ $row['days_overdue'] }}</td>
    </tr>
    @endforeach
  </tbody>
</table>
@endif
@endforeach

<div class="footer">Total overdue: {{ $summary['total_overdue'] }} periods · Total balance: ₱{{ number_format($summary['total_balance'],2) }} · Total penalty: ₱{{ number_format($summary['total_penalty'],2) }}</div>
</body>
</html>
