{{-- resources/views/reports/outstanding.blade.php --}}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: DejaVu Sans, sans-serif; font-size: 8.5px; color: #1C1F26; margin: 20px; }
  .letterhead { text-align: center; border-bottom: 1.5px solid #1C1F26; padding-bottom: 8px; margin-bottom: 12px; }
  .letterhead h1 { font-size: 12px; font-weight: bold; margin: 0 0 2px; }
  .letterhead p  { font-size: 8px; color: #555; margin: 0; }
  .letterhead h2 { font-size: 14px; font-weight: bold; margin: 6px 0 2px; }
  .meta { font-size: 8px; color: #555; margin-bottom: 12px; display: flex; justify-content: space-between; }
  .summary-row { display: flex; gap: 8px; margin-bottom: 14px; }
  .stat { background: #f5f5f0; border: 0.5px solid #ddd; border-radius: 4px; padding: 6px 10px; flex: 1; }
  .stat-label { font-size: 7px; text-transform: uppercase; letter-spacing: .4px; color: #666; }
  .stat-val   { font-size: 12px; font-weight: bold; }
  table { width: 100%; border-collapse: collapse; }
  th { background: #1C3557; color: #fff; font-size: 7.5px; text-transform: uppercase; letter-spacing:.3px; padding: 5px 6px; text-align: left; }
  td { padding: 4px 6px; border-bottom: 0.5px solid #e0e0e0; font-size: 8px; }
  .right { text-align: right; }
  .total-row td { font-weight: bold; background: #f0f0ea; border-top: 1px solid #aaa; }
  .danger { color: #A32D2D; }
  .footer { margin-top: 16px; font-size: 7px; color: #888; border-top: 0.5px solid #ccc; padding-top: 6px; display: flex; justify-content: space-between; }
</style>
</head>
<body>
<div class="letterhead">
  <h1>{{ strtoupper($profile->name) }}</h1>
  <p>{{ $profile->address }} · CDA Reg. No. {{ $profile->cda_reg_no ?? '___' }}</p>
  <h2>OUTSTANDING LOAN BALANCE REPORT</h2>
</div>
<div class="meta">
  <span>@if(!empty($filters['company'])) Company: {{ $filters['company'] }} @else All companies @endif</span>
  <span>Generated by: {{ $generated_by }} · {{ $generated_at }}</span>
</div>

<div class="summary-row">
  <div class="stat"><div class="stat-label">Active loans</div><div class="stat-val">{{ $summary['total_loans'] }}</div></div>
  <div class="stat"><div class="stat-label">Total outstanding</div><div class="stat-val">₱{{ number_format($summary['total_outstanding'],2) }}</div></div>
  <div class="stat"><div class="stat-label">Total overdue</div><div class="stat-val danger">₱{{ number_format($summary['total_overdue'],2) }}</div></div>
  <div class="stat"><div class="stat-label">Loans w/ overdue</div><div class="stat-val danger">{{ $summary['loans_with_overdue'] }}</div></div>
</div>

<table>
  <thead><tr>
    <th>Member</th><th>Member #</th><th>Company</th><th>Loan #</th>
    <th>Type</th><th>Status</th>
    <th class="right">Original (₱)</th><th class="right">Paid (₱)</th>
    <th class="right">Balance (₱)</th><th class="right">Overdue (₱)</th>
  </tr></thead>
  <tbody>
    @foreach($rows as $row)
    <tr>
      <td>{{ $row['member_name'] }}</td>
      <td>{{ $row['member_no'] }}</td>
      <td>{{ $row['company'] }}</td>
      <td>{{ $row['loan_no'] }}</td>
      <td>{{ $row['loan_type_label'] }}</td>
      <td>{{ $row['loan_status'] }}</td>
      <td class="right">{{ number_format($row['original_amount'],2) }}</td>
      <td class="right">{{ number_format($row['total_paid'],2) }}</td>
      <td class="right">{{ number_format($row['remaining_balance'],2) }}</td>
      <td class="right @if($row['overdue_balance']>0) danger @endif">{{ number_format($row['overdue_balance'],2) }}</td>
    </tr>
    @endforeach
    <tr class="total-row">
      <td colspan="6">TOTAL ({{ $summary['total_loans'] }} loans)</td>
      <td class="right">{{ number_format($summary['total_original'],2) }}</td>
      <td class="right">{{ number_format($summary['total_paid'],2) }}</td>
      <td class="right">{{ number_format($summary['total_outstanding'],2) }}</td>
      <td class="right danger">{{ number_format($summary['total_overdue'],2) }}</td>
    </tr>
  </tbody>
</table>

<div class="footer">
  <span>{{ $profile->coop_signatory ?? 'COOP Manager / Loan Officer' }}</span>
  <span>This report was generated electronically. Total penalty accrued: ₱{{ number_format($summary['total_penalty'],2) }}</span>
</div>
</body>
</html>
