<?php
namespace App\Services;

use App\Models\CoopProfile;
use Illuminate\Support\Facades\Auth;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use Barryvdh\DomPDF\Facade\Pdf;

class ExportService
{
    private CoopProfile $profile;

    public function __construct()
    {
        $this->profile = CoopProfile::current();
    }

    // ── Excel ────────────────────────────────────────────────

    public function toExcel(string $reportType, array $data, array $options = []): string
    {
        $spreadsheet = new Spreadsheet();
        $sheet       = $spreadsheet->getActiveSheet();

        match ($reportType) {
            'collection'  => $this->buildCollectionSheet($sheet, $data),
            'aging'       => $this->buildAgingSheet($sheet, $data),
            'outstanding' => $this->buildOutstandingSheet($sheet, $data),
        };

        if ($options['include_summary_sheet'] ?? false) {
            $this->buildSummarySheet($spreadsheet->createSheet(), $reportType, $data);
        }

        $path = storage_path('app/exports/report_' . $reportType . '_' . now()->format('Ymd_His') . '.xlsx');
        @mkdir(dirname($path), 0755, true);
        (new Xlsx($spreadsheet))->save($path);
        return $path;
    }

    private function letterheadRows(\PhpOffice\PhpSpreadsheet\Worksheet\Worksheet $sheet, string $title, int $colCount): int
    {
        $lastCol = \PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex($colCount);
        $sheet->mergeCells("A1:{$lastCol}1");
        $sheet->setCellValue('A1', strtoupper($this->profile->name));
        $sheet->getStyle('A1')->getFont()->setBold(true)->setSize(13);
        $sheet->getStyle('A1')->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);

        $sheet->mergeCells("A2:{$lastCol}2");
        $sheet->setCellValue('A2', $this->profile->address . '  ·  CDA Reg. No. ' . ($this->profile->cda_reg_no ?? '___'));
        $sheet->getStyle('A2')->getFont()->setSize(9)->setItalic(true);
        $sheet->getStyle('A2')->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);

        $sheet->mergeCells("A3:{$lastCol}3");
        $sheet->setCellValue('A3', strtoupper($title));
        $sheet->getStyle('A3')->getFont()->setBold(true)->setSize(12);
        $sheet->getStyle('A3')->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);

        $sheet->mergeCells("A4:{$lastCol}4");
        $sheet->setCellValue('A4', 'Generated by: ' . Auth::user()?->name . '  ·  ' . now()->format('F d, Y  H:i'));
        $sheet->getStyle('A4')->getFont()->setSize(9);
        $sheet->getStyle('A4')->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);

        $sheet->getRowDimension(1)->setRowHeight(18);
        $sheet->getRowDimension(3)->setRowHeight(18);
        return 5;
    }

    private function headerStyle(\PhpOffice\PhpSpreadsheet\Worksheet\Worksheet $sheet, string $range): void
    {
        $sheet->getStyle($range)->applyFromArray([
            'font'      => ['bold' => true, 'color' => ['rgb' => 'FFFFFF']],
            'fill'      => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => '1C3557']],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
        ]);
    }

    private function pesoFormat(): string { return '₱#,##0.00'; }

    private function buildCollectionSheet(\PhpOffice\PhpSpreadsheet\Worksheet\Worksheet $sheet, array $data): void
    {
        $sheet->setTitle('Collection Summary');
        $row = $this->letterheadRows($sheet, 'Monthly Collection Summary', 7);
        $sheet->mergeCells("A{$row}:G{$row}");
        $sheet->setCellValue("A{$row}", "Period: {$data['date_from']} to {$data['date_to']}");
        $row++;

        $headers = ['Loan Type', 'Periods', 'Paid', 'Expected (₱)', 'Collected (₱)', 'Shortfall (₱)', 'Rate (%)'];
        foreach ($headers as $i => $h) {
            $col = \PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex($i + 1);
            $sheet->setCellValue("{$col}{$row}", $h);
        }
        $this->headerStyle($sheet, "A{$row}:G{$row}");
        $row++;

        $rows = $data['by_loan_type'] ?? $data['rows'] ?? [];
        foreach ($rows as $r) {
            $sheet->setCellValue("A{$row}", $r['label'] ?? $r['loan_type_label']);
            $sheet->setCellValue("B{$row}", $r['period_count']);
            $sheet->setCellValue("C{$row}", $r['paid_count']);
            $sheet->setCellValue("D{$row}", $r['expected']);
            $sheet->setCellValue("E{$row}", $r['collected']);
            $sheet->setCellValue("F{$row}", $r['shortfall']);
            $sheet->setCellValue("G{$row}", $r['rate']);
            $sheet->getStyle("D{$row}:F{$row}")->getNumberFormat()->setFormatCode($this->pesoFormat());
            $row++;
        }

        $s = $data['summary'];
        $sheet->setCellValue("A{$row}", 'TOTAL');
        $sheet->setCellValue("B{$row}", $s['total_periods']);
        $sheet->setCellValue("C{$row}", $s['paid_periods']);
        $sheet->setCellValue("D{$row}", $s['total_expected']);
        $sheet->setCellValue("E{$row}", $s['total_collected']);
        $sheet->setCellValue("F{$row}", $s['total_shortfall']);
        $sheet->setCellValue("G{$row}", $s['collection_rate']);
        $sheet->getStyle("A{$row}:G{$row}")->getFont()->setBold(true);
        $sheet->getStyle("D{$row}:F{$row}")->getNumberFormat()->setFormatCode($this->pesoFormat());

        foreach (range('A', 'G') as $col) $sheet->getColumnDimension($col)->setAutoSize(true);
    }

    private function buildAgingSheet(\PhpOffice\PhpSpreadsheet\Worksheet\Worksheet $sheet, array $data): void
    {
        $sheet->setTitle('Aging Report');
        $row = $this->letterheadRows($sheet, 'Loan Aging Report', 8);
        $sheet->mergeCells("A{$row}:H{$row}");
        $sheet->setCellValue("A{$row}", "As of: " . $data['as_of_date']);
        $row++;

        $headers = ['Member', 'Member #', 'Loan #', 'Type', 'Due Date', 'Balance (₱)', 'Penalty (₱)', 'Days Overdue'];
        foreach ($headers as $i => $h) {
            $col = \PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex($i + 1);
            $sheet->setCellValue("{$col}{$row}", $h);
        }
        $this->headerStyle($sheet, "A{$row}:H{$row}");
        $row++;

        $allRows = array_merge(
            $data['buckets']['0_30'],
            $data['buckets']['31_60'],
            $data['buckets']['61_90'],
            $data['buckets']['90_plus']
        );

        foreach ($allRows as $r) {
            $sheet->setCellValue("A{$row}", $r['member_name']);
            $sheet->setCellValue("B{$row}", $r['member_no']);
            $sheet->setCellValue("C{$row}", $r['loan_no']);
            $sheet->setCellValue("D{$row}", $r['loan_type_label']);
            $sheet->setCellValue("E{$row}", $r['due_date']);
            $sheet->setCellValue("F{$row}", $r['balance']);
            $sheet->setCellValue("G{$row}", $r['penalty_amount']);
            $sheet->setCellValue("H{$row}", $r['days_overdue']);
            $sheet->getStyle("F{$row}:G{$row}")->getNumberFormat()->setFormatCode($this->pesoFormat());
            if ($r['days_overdue'] > 90) {
                $sheet->getStyle("A{$row}:H{$row}")->getFill()
                    ->setFillType(Fill::FILL_SOLID)->getStartColor()->setRGB('FFEBEB');
            }
            $row++;
        }

        foreach (range('A', 'H') as $col) $sheet->getColumnDimension($col)->setAutoSize(true);
    }

    private function buildOutstandingSheet(\PhpOffice\PhpSpreadsheet\Worksheet\Worksheet $sheet, array $data): void
    {
        $sheet->setTitle('Outstanding Balance');
        $row = $this->letterheadRows($sheet, 'Outstanding Loan Balance Report', 9);
        $row++;

        $headers = ['Member', 'Member #', 'Company', 'Loan #', 'Type', 'Status', 'Original (₱)', 'Paid (₱)', 'Balance (₱)', 'Overdue (₱)'];
        foreach ($headers as $i => $h) {
            $col = \PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex($i + 1);
            $sheet->setCellValue("{$col}{$row}", $h);
        }
        $this->headerStyle($sheet, "A{$row}:J{$row}");
        $row++;

        foreach ($data['rows'] as $r) {
            $sheet->setCellValue("A{$row}", $r['member_name']);
            $sheet->setCellValue("B{$row}", $r['member_no']);
            $sheet->setCellValue("C{$row}", $r['company']);
            $sheet->setCellValue("D{$row}", $r['loan_no']);
            $sheet->setCellValue("E{$row}", $r['loan_type_label']);
            $sheet->setCellValue("F{$row}", $r['loan_status']);
            $sheet->setCellValue("G{$row}", $r['original_amount']);
            $sheet->setCellValue("H{$row}", $r['total_paid']);
            $sheet->setCellValue("I{$row}", $r['remaining_balance']);
            $sheet->setCellValue("J{$row}", $r['overdue_balance']);
            $sheet->getStyle("G{$row}:J{$row}")->getNumberFormat()->setFormatCode($this->pesoFormat());
            $row++;
        }

        $s = $data['summary'];
        $sheet->setCellValue("A{$row}", 'TOTAL');
        $sheet->setCellValue("G{$row}", $s['total_original']);
        $sheet->setCellValue("H{$row}", $s['total_paid']);
        $sheet->setCellValue("I{$row}", $s['total_outstanding']);
        $sheet->setCellValue("J{$row}", $s['total_overdue']);
        $sheet->getStyle("A{$row}:J{$row}")->getFont()->setBold(true);
        $sheet->getStyle("G{$row}:J{$row}")->getNumberFormat()->setFormatCode($this->pesoFormat());

        foreach (range('A', 'J') as $col) $sheet->getColumnDimension($col)->setAutoSize(true);
    }

    private function buildSummarySheet(\PhpOffice\PhpSpreadsheet\Worksheet\Worksheet $sheet, string $type, array $data): void
    {
        $sheet->setTitle('Summary');
        $sheet->setCellValue('A1', 'Report type');
        $sheet->setCellValue('B1', ucfirst(str_replace('_', ' ', $type)));
        $sheet->setCellValue('A2', 'Generated by');
        $sheet->setCellValue('B2', Auth::user()?->name);
        $sheet->setCellValue('A3', 'Generated at');
        $sheet->setCellValue('B3', now()->format('F d, Y H:i'));
        $sheet->getStyle('A1:A3')->getFont()->setBold(true);
        $row = 5;
        foreach ($data['summary'] as $key => $value) {
            $sheet->setCellValue("A{$row}", ucwords(str_replace('_', ' ', $key)));
            $sheet->setCellValue("B{$row}", is_array($value) ? json_encode($value) : $value);
            $row++;
        }
        $sheet->getColumnDimension('A')->setWidth(30);
        $sheet->getColumnDimension('B')->setWidth(20);
    }

    // ── PDF ──────────────────────────────────────────────────

    public function toPdf(string $reportType, array $data): string
    {
        $view = "reports.{$reportType}";
        $pdf  = Pdf::loadView($view, array_merge($data, [
            'profile'      => $this->profile,
            'generated_by' => Auth::user()?->name,
            'generated_at' => now()->format('F d, Y  H:i'),
        ]))->setPaper('a4', 'landscape');

        $path = storage_path('app/exports/report_' . $reportType . '_' . now()->format('Ymd_His') . '.pdf');
        @mkdir(dirname($path), 0755, true);
        $pdf->save($path);
        return $path;
    }
}
