{{-- resources/views/reports/collection.blade.php --}}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: DejaVu Sans, sans-serif; font-size: 9px; color: #1C1F26; margin: 20px; }
  .letterhead { text-align: center; border-bottom: 1.5px solid #1C1F26; padding-bottom: 8px; margin-bottom: 10px; }
  .letterhead h1 { font-size: 12px; font-weight: bold; margin: 0 0 2px; }
  .letterhead p  { font-size: 8px; color: #555; margin: 0; }
  .letterhead h2 { font-size: 14px; font-weight: bold; margin: 6px 0 2px; }
  .meta { font-size: 8px; color: #555; margin-bottom: 10px; display: flex; justify-content: space-between; }
  .filter-line { font-size: 8px; color: #555; margin-bottom: 8px; }
  .summary-row { display: flex; gap: 8px; margin-bottom: 12px; }
  .stat { background: #f5f5f0; border: 0.5px solid #ddd; border-radius: 4px; padding: 6px 10px; flex: 1; }
  .stat-label { font-size: 7px; text-transform: uppercase; letter-spacing: .4px; color: #666; }
  .stat-val   { font-size: 13px; font-weight: bold; }
  .section-title { font-size: 9px; font-weight: bold; text-transform: uppercase; letter-spacing: .5px;
    color: #fff; background: #1C3557; padding: 4px 8px; margin: 10px 0 0; }
  table { width: 100%; border-collapse: collapse; }
  th { background: #e8eef5; color: #1C1F26; font-size: 7.5px; text-transform: uppercase; padding: 4px 8px; text-align: left; }
  td { padding: 4px 8px; border-bottom: 0.5px solid #e8e8e8; font-size: 8.5px; }
  .right { text-align: right; }
  .total-row td { font-weight: bold; background: #f0f0ea; border-top: 1px solid #aaa; }
  .danger { color: #A32D2D; }
  .success { color: #0F6E56; }
  .footer { margin-top: 14px; font-size: 7px; color: #888; border-top: 0.5px solid #ccc; padding-top: 5px; display:flex; justify-content:space-between; }
</style>
</head>
<body>
<div class="letterhead">
  <h1>{{ strtoupper($profile->name) }}</h1>
  <p>{{ $profile->address }} · CDA Reg. No. {{ $profile->cda_reg_no ?? '___' }}</p>
  <h2>MONTHLY COLLECTION SUMMARY</h2>
</div>
<div class="meta">
  <span>Period: {{ $date_from }} to {{ $date_to }}</span>
  <span>Generated by: {{ $generated_by }} · {{ $generated_at }}</span>
</div>
@if(!empty($filters['company']) || !empty($filters['department']))
<div class="filter-line">
  Filters:
  @if(!empty($filters['company'])) Company: {{ $filters['company'] }} @endif
  @if(!empty($filters['department'])) · Dept: {{ $filters['department'] }} @endif
</div>
@endif

<div class="summary-row">
  <div class="stat"><div class="stat-label">Expected</div><div class="stat-val">₱{{ number_format($summary['total_expected'],2) }}</div></div>
  <div class="stat"><div class="stat-label">Collected</div><div class="stat-val success">₱{{ number_format($summary['total_collected'],2) }}</div></div>
  <div class="stat"><div class="stat-label">Shortfall</div><div class="stat-val danger">₱{{ number_format($summary['total_shortfall'],2) }}</div></div>
  <div class="stat"><div class="stat-label">Penalty</div><div class="stat-val danger">₱{{ number_format($summary['total_penalty'],2) }}</div></div>
  <div class="stat"><div class="stat-label">Rate</div><div class="stat-val">{{ $summary['collection_rate'] }}%</div></div>
</div>

{{-- Breakdown by loan type --}}
<div class="section-title">By loan type</div>
<table>
  <thead><tr>
    <th>Loan type</th><th class="right">Periods</th><th class="right">Paid</th>
    <th class="right">Expected (₱)</th><th class="right">Collected (₱)</th>
    <th class="right">Shortfall (₱)</th><th class="right">Rate</th>
  </tr></thead>
  <tbody>
    @foreach($by_loan_type as $row)
    <tr>
      <td>{{ $row['label'] }}</td>
      <td class="right">{{ $row['period_count'] }}</td>
      <td class="right">{{ $row['paid_count'] }}</td>
      <td class="right">{{ number_format($row['expected'],2) }}</td>
      <td class="right success">{{ number_format($row['collected'],2) }}</td>
      <td class="right @if($row['shortfall']>0) danger @endif">{{ number_format($row['shortfall'],2) }}</td>
      <td class="right">{{ $row['rate'] }}%</td>
    </tr>
    @endforeach
    <tr class="total-row">
      <td>Total</td>
      <td class="right">{{ $summary['total_periods'] }}</td>
      <td class="right">{{ $summary['paid_periods'] }}</td>
      <td class="right">{{ number_format($summary['total_expected'],2) }}</td>
      <td class="right success">{{ number_format($summary['total_collected'],2) }}</td>
      <td class="right danger">{{ number_format($summary['total_shortfall'],2) }}</td>
      <td class="right">{{ $summary['collection_rate'] }}%</td>
    </tr>
  </tbody>
</table>

{{-- Breakdown by loan status --}}
<div class="section-title">By loan status</div>
<table>
  <thead><tr>
    <th>Loan status</th><th class="right">Periods</th><th class="right">Paid</th>
    <th class="right">Expected (₱)</th><th class="right">Collected (₱)</th>
    <th class="right">Shortfall (₱)</th><th class="right">Rate</th>
  </tr></thead>
  <tbody>
    @foreach($by_loan_status as $row)
    <tr>
      <td>{{ $row['label'] }}</td>
      <td class="right">{{ $row['period_count'] }}</td>
      <td class="right">{{ $row['paid_count'] }}</td>
      <td class="right">{{ number_format($row['expected'],2) }}</td>
      <td class="right success">{{ number_format($row['collected'],2) }}</td>
      <td class="right @if($row['shortfall']>0) danger @endif">{{ number_format($row['shortfall'],2) }}</td>
      <td class="right">{{ $row['rate'] }}%</td>
    </tr>
    @endforeach
  </tbody>
</table>

<div class="footer">
  <span>{{ $profile->coop_signatory ?? 'COOP Manager' }}</span>
  <span>Electronically generated — valid without signature</span>
</div>
</body>
</html>
